Adapt extension for Quarkus 3.31+
For some reason, Quarkus 3.31+ is more picky on how extensions should
look like. We're getting test errors when building our apps using the
quarkus-logging-kafka and Quarkus 3.31.x.

```
Error:  Caused by: java.lang.IllegalArgumentException: Run time configuration cannot be consumed in Build Steps, use RuntimeValue<org.jboss.pnc.logging.kafka.KafkaLogConfig> in a @Recorder constructor instead at org.jboss.pnc.logging.kafka.KafkaLogConfig config of io.quarkus.deployment.builditem.LogHandlerBuildItem org.jboss.pnc.logging.kafka.deployment.KafkaLogHandlerProcessor.build(org.jboss.pnc.logging.kafka.KafkaLogHandlerRecorder,org.jboss.pnc.logging.kafka.KafkaLogConfig) of class org.jboss.pnc.logging.kafka.deployment.KafkaLogHandlerProcessor
Error:  	at io.quarkus.deployment.ExtensionLoader.reportError(ExtensionLoader.java:997)
Error:  	at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:621)

```
https://github.com/project-ncl/causeway/actions/runs/22025249945/job/63640775477?pr=446

This is caused by us providing the KafkaLogConfig as a parameter for the
initializeHandler. After playing around, this current version makes
Quarkus 3.31 happy.